### ISSUE TITLE
Changing material in MATL editor resets animation to frame 1

### ISSUE THREAD

**Issue by zrksyd** [ScanMountGoat/ssbh_editor#105]
If a boolean or texture is changed in the material editor, the model will revert to frame 1 and go back to normal once you click play on the animation agian.

**Comment by ScanMountGoat** [comment]
If the animation is playing, material animations will update as expected even while using the matl editor. If the animation is paused, editing a value in the matl editor will override the animation values. ssbh_wgpu updates the entire material when animating or editing materials. This is for performance reasons and is also easier to maintain.  I don't think it's worth the added complexity to try and fix, since material animations tend to override most of the parameters anyway.
