### ISSUE TITLE
Incorrect character rendering Intel 4000 series

### ISSUE THREAD

**Issue by theairbud** [ScanMountGoat/ssbh_editor#117]
![ssbh_editor](https://user-images.githubusercontent.com/89312464/196260658-c5b4668f-d018-4517-a294-93b632802bbc.jpg)

Every time I try to load a character in SSBH Editor, all of the meshes curve into a black sphere, whether it's a vanilla character or a modded character. I can load the same characters fine in the latest version of CrossModGUI. 

I'm running Windows DX12, the latest C++ Runtime. 

Please help :)

**Comment by ScanMountGoat** [comment]
What GPU do you have? If your computer doesn't have a graphics card, this would be the name of the processor or CPU. Try unchecking "Enable Vertex Skinning" in Menu > Render Settings. You can also try changing the shading mode to something like "Basic" or "Normal0".

**Comment by theairbud** [comment]
I tried your suggestions, and nothing changed (except that when I change the debug shading options to Albedo, the black sphere becomes a combination of light orange and black.) 

I have an Intel Iris Pro Graphics 5200 and an Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz.

**Comment by ScanMountGoat** [comment]
Your CPU is from an older generation that might not support Vulkan properly. SSBH Editor will try DX12 if Vulkan doesn't work, which should run fine on your system. The issue is that if the GPU claims to suport Vulkan, SSBH Editor won't try DX12 at all. This isn't something I can easily detect. I've seen this issue a few other times on similar hardware. My old PC with an Intel 4670k doesn't work, for example.

There are two solutions that I may consider going forward. I can default to DX12, which takes longer to load but tends to run better on Windows. I can also add an option to let people choose the API on Windows. This is an easy change to code, but I'll need to think about how it will effect the experience for the majority of users. I'll try and look into it and let you know if I make any changes for the next release.

**Comment by theairbud** [comment]
Wow, thank you so much for considering to implement this feature for older systems. I really appreciate it.

**Comment by xNhil0** [comment]
Hmm yeah. Mine is Intel(R) HD Graphics Family on a laptop.

**Comment by theairbud** [comment]
I followed all of the steps, opened the program (ssbh 7.2), opened a character file and got the same the results. The black sphere of doom persists.

**Comment by ScanMountGoat** [comment]
This is a driver limitation and isn't really something I can fix on my end at the moment. See my comment on #129.

**Comment by theairbud** [comment]
Ahh, I see. Thanks for the clarification and all the work you put into searching for a solution.
