### ISSUE TITLE
Black Sphere of Doom Intel 4000 series

### ISSUE THREAD

**Issue by xNhil0** [ScanMountGoat/ssbh_editor#129]
![ssbhpls](https://user-images.githubusercontent.com/108420099/204041504-2f9f0873-16d8-4f6e-9810-03bc82a15057.png)

Bare with me this is my first time submitting an issue on github. But anyway as you can see from the pic, when I open a vanilla c00 directory, it will not display it under any circumstance. I've tried different characters. This program started doing this for me a couple updates ago, it used to display characters just fine. Not sure what could have changed or if I did something. I tried re-downloading old versions, but those won't work anymore either. I never tried viewing stages or anything other than c00 stuff. Left panel properly previews textures, just the central viewport has a problem.

**Comment by ScanMountGoat** [comment]
What GPU do you have? This looks similar to the issue in #117.

**Comment by xNhil0** [comment]
Hmm yeah. Mine is Intel(R) HD Graphics Family on a laptop.

**Comment by xNhil0** [comment]
CPU is Intel (R) Core(TM) i7-4600U CPU @ 2.10GHz

**Comment by ScanMountGoat** [comment]
Does it work properly if you set DX12 in the preferences and then restart the application? You can also launch from commandline as `ssbh_editor.exe --backend DX12`.

**Comment by xNhil0** [comment]
No dice.

**Comment by ScanMountGoat** [comment]
Apparently intel disabled DX12 in one of their driver updates a while back due to security vulnerabilties. You can find more information online if you search around. This isn't really something I can fix since there's no way for me to support DX11 at this time. Intel Haswell was released right around when Vulkan and DX12 were new, so the driver compatibility isn't great.

**Comment by xNhil0** [comment]
Ah, unfortunate. Thanks for the timely assistance.
