### ISSUE TITLE
Default WrapMode should be Repeat instead of ClampToEdge

### ISSUE THREAD

**Issue by zrksyd** [ScanMountGoat/ssbh_editor#131]
I'm not sure of the protocol to contribute to ssbh_lib but here is my pull request. Applying most of the material presets give errors because the Sampler Wrap Mode gets changed to ClampToEdge, which will cause SSBH Editor to throw errors.
https://github.com/ultimate-research/ssbh_lib/pull/144

**Comment by ScanMountGoat** [comment]
Defaulting to ClampToEdge in ssbh_lib/ssbh_data is intentional since it's the only wrap mode that makes sense for all texture types. Cube maps should always use ClampToEdge. 2D textures sometimes use other wrap modes like Repeat or MirroredRepeat as needed. SSBH Editor only generates validation errors if the mesh has UVs outside the 0.0 to 1.0 range and uses ClampToBorder or ClampToEdge. Clamping the UVs like this won't cause glitches in game but probably isn't intentional.

If you wanted to prevent these errors when applying presets, you could default to Repeat but only for the 2D textures. The easiest would probably be to modify the presets themselves. This won't automatically update people's existing preset files, however. I don't have a plan in place at the moment for how to handle updating preset files with new application versions. Another option is to change the `apply_preset` function and ignore the wrap mode made in the preset.
