### ISSUE TITLE
Incorrect UV animation for Mario h14gekikarawait.nuanmb

### ISSUE THREAD

**Issue by SushiiZ** [ScanMountGoat/ssbh_editor#147]
I just noticed that ssbh editor doesn't actually display resized pupils properly, it scales them in a weird way and doesn't reflect how it scales ingame 

![image](https://user-images.githubusercontent.com/51277271/225812526-20ab5d62-41ae-4437-9e8c-09eba983204b.png)
![image2](https://user-images.githubusercontent.com/51277271/225812529-3e5bc044-1cb0-4a24-870d-d16c8941c19b.png)
![2023031700245100-0E7DF678130F4F0FA2C88AE72B47AFDF](https://user-images.githubusercontent.com/51277271/225812537-460b490d-5cc1-402a-bdb0-7aeb84e10c28.jpg)

it'd be nice to have this display properly, not sure where it gets lost in translation but hopefully you can fix it.

**Comment by ScanMountGoat** [comment]
Which animation is that?

**Comment by ssbucarlos** [comment]
fighter/mario/motion/body/c00/h14gekikarawait.nuanmb

**Comment by ScanMountGoat** [comment]
It looks like the translation components in CustomVector31.ZW need to be negated differently for h14gekikarawait.nuanmb compared to a00wait2.nuanmb. I'll check later and see if there are any parameters controlling this.

**Comment by SushiiZ** [comment]
oh interesting, I also think it's safe to assume this is how it works for any character who has pupils that shrink who don't have separate meshes for them

**Comment by ScanMountGoat** [comment]
The parameters are similar for both animations other than the scale values. I've ported the relevant portion of the UV transform shader code from in game to resolve the issue. This will be fixed in the next release. Thanks for notifying me about the issue.
![image](https://user-images.githubusercontent.com/23301691/226053285-f7fd1f7b-066e-44be-a274-2ffbc6d4abd9.png)
