### ISSUE TITLE
Viewport posterization due to 8-bit gamma conversions

### ISSUE THREAD

**Issue by schiggysmallz** [ScanMountGoat/ssbh_editor#178]
i noticed that with 0.9.2 there is a drop in quality for the rendering.
dunno how to describe it exactly but it looks like some sort of posterization.
its not the model or textures fault as it also happens with vanilla models.
heres a pic from 0.8.4
![image](https://github.com/ScanMountGoat/ssbh_editor/assets/45839667/f6c13f7f-9337-4f70-a36b-56d7ef80f234)
and this is 0.9.2
![image](https://github.com/ScanMountGoat/ssbh_editor/assets/45839667/e131956e-9865-46f3-95c5-0873e3744f51)
you can clearly see the difference and it also can see it on the bloom
heres an even more extreme example
0.8.4
![image](https://github.com/ScanMountGoat/ssbh_editor/assets/45839667/ec5cb939-633c-4837-b568-d9a640f8a839)
0.9.2
![image](https://github.com/ScanMountGoat/ssbh_editor/assets/45839667/bf9539d3-d188-4716-9281-d445c8f71f0a)

**Comment by ScanMountGoat** [comment]
Thanks for providing the screenshots. It looks like the internal bit depth isn't high enough to handle some of the conversions to and from sRGB gamma due to some recent UI changes with 0.9.2. The effect is similar to why the in game UI looks bad on dark colors. The bloom renders at a slightly lower internal resolution, but that shouldn't make a huge difference.

I should be able to get this fixed for a 0.9.3 release, but it isn't a high priority at the moment. SSBH Editor 0.8.4 should be fine to use for now other than a few rendering bugs that were fixed for 0.9.x.
