### ISSUE TITLE
Reorder materials in Matl Editor

### ISSUE THREAD

**Issue by BeyondSmash** [ScanMountGoat/ssbh_editor#181]
It would be very useful to sort materials manually via Hamburger button drag when the menu of materials is open. You can use the current drag sort function in model.numshb. Also sorting alphabetically is handy too.

https://github.com/ScanMountGoat/ssbh_editor/assets/110957189/d36a789f-36fb-4138-97e6-9bd0ca3b1f24

**Comment by ScanMountGoat** [comment]
Materials are referenced by name, so there wouldn't be any in game benefits for adjusting their order. I could see how this may be helpful for sorting the materials visually in the editor. I'm not sure how well the drag and drop UI will integrate with the drop down widget.

**Comment by BeyondSmash** [comment]
> Materials are referenced by name, so there wouldn't be any in game benefits for adjusting their order. I could see how this may be helpful for sorting the materials visually in the editor. I'm not sure how well the drag and drop UI will integrate with the drop down widget.

It is definitely not beneficial in-game. My whole point is for my workflow in SSBH and to deter the confusion of how materials export to SSBH. It becomes random and scattered. If you are concerned of integrating drag and drop UI with the drop down widget, then you can create a "Sort" button that creates a separate pop-up menu where it all can be done instead of combining with the drop down menu.

**Comment by ScanMountGoat** [comment]
A manually sortable drop down list sounds cumbersome to use due to the small space and isn't something I've seen before. A better solution would probably be to have drag and drop handles like the other editors with materials in a list view. There's space to add a list of selectable materials on the left similar to the Anim Editor. I'm also fine with someone adding a new header section with a menu option for Material > Sort Alphabetically.

This seems easy to implement in terms of code, but I don't have a clear idea of exactly how this should work. I can try and give more detailed feedback later if someone wants to prototype a solution.

**Comment by zrksyd** [comment]
I attempted to implement the sorting but
`matl.entries.sort_by(|a, b| a.partial_cmp(b.material_label).unwrap());`
Didn't work because MatlEntryData doesn't have the PartialOrd trait. Is there a better way to do this or does this require editing the ssbh_lib crate?

**Comment by ScanMountGoat** [comment]
You could use sort_by_key with a closure that returns the material name field. It's a little clearer than sort_by in my opinion.

**Comment by ScanMountGoat** [comment]
You can now manually reorder materials using drag and drop similar to the other editors on the latest commit.
