### ISSUE TITLE
Ability to render images as png/gif length of animation

### ISSUE THREAD

**Issue by imod-commission** [ScanMountGoat/ssbh_editor#3]
Ability to render images as png, similar to StudioSB and Crossmod, if GIF rendering is possible it would be even awesome

**Comment by ScanMountGoat** [comment]
This is definitely doable to add at some point.

**Comment by zrksyd** [comment]
I saw screenshot saving was added. Is GIF rendering being added soon too?

**Comment by ScanMountGoat** [comment]
GIF rendering is more involved, so it probably won't be in the next update.

**Comment by ScanMountGoat** [comment]
The only thing left to be implemented for this is saving with a transparent background when rendering as an image sequence with a format that supports transparency like PNG.

**Comment by zrksyd** [comment]
Does that include GIF too because I think GIF does have 1 bit transparency.

**Comment by joaorb64** [comment]
Thanks for the update! I was able to generate videos with transparency like these:

[output.webm](https://user-images.githubusercontent.com/7636440/214275357-6355a4a0-30b6-4ab6-9960-9c08001d70f7.webm)

[output2.webm](https://user-images.githubusercontent.com/7636440/214275187-d0513c93-8b63-4e99-aa9a-e5d05d3ddd84.webm)

Transparency will surely help, since I couldn't get rid of the pink background completely in my examples.

**Comment by ScanMountGoat** [comment]
Transparency will be in the next release for PNG and GIF.
