### ISSUE TITLE
Visualize material assignments in matl editor

### ISSUE THREAD

**Issue by Messyproduct** [ScanMountGoat/ssbh_editor#44]
### **Mesh Assigned Material Visualizer:**
Way of easily seeing which material is assigned to meshes Ala Crossmod
![image](https://user-images.githubusercontent.com/109486492/179426183-4765f8a3-e4df-4ed8-9366-e3e49e62bf04.png)

### **Parameter Editing Tweak:**
Make single left click open the text parameter for editing rather than setting value. 

Current: Left clicking changes value before text editing can occur
![image](https://i.gyazo.com/fb81b18041591749829be6aa9c59a4d5.gif)

Suggested: Left click opens text for manual editing, left click and drag allows for easy tweaks (like Blender)
![image](https://i.gyazo.com/328619a4d84ec2073fabb2e0694b9129.gif)

**Comment by ScanMountGoat** [comment]
In the future, please create separate issues if there are two feature requests. This makes it easier to track on my end.

Showing what material is selected in the viewport is planned for the next release. I won't be using the exact same system as Cross Mod since it stops working well after about a dozen materials. Numatb files can easily have hundreds of materials for stages.

**Comment by ScanMountGoat** [comment]
Your second suggestion is tracked in #45.

**Comment by Messyproduct** [comment]
Got it noted. Thanks for the feedback
