### ISSUE TITLE
Bottom panel layout

### ISSUE THREAD

**Issue by zrksyd** [ScanMountGoat/ssbh_editor#68]
I saw you had a to-do comment about improving the layout. I attempted to implement this myself but the ui.end_row() line break was giving me issues since it's not wrapped in a container. So I made a mockup in MS Paint of what I was trying to do.

![image](https://user-images.githubusercontent.com/6856627/184672007-417a81a7-e5e2-429f-a679-56de8e7f75ca.png)

**Comment by zrksyd** [comment]
Actually switch speed and loop and make the checkmark of the right side of the label to be more consistent + making it more like BrawlBox / BrawlCrate like this:
![image](https://user-images.githubusercontent.com/6856627/184672007-417a81a7-e5e2-429f-a679-56de8e7f75ca.png)

**Comment by ScanMountGoat** [comment]
If you need a reference, I would look at content creation applications like Blender, Max, or Maya. These are the applications people will be using to author animations, so it makes the most sense to match their overall look and feel. The current implementation was just simple to code. I'm also open to making custom UI controls for the animation bar if it would improve the experience.

**Comment by zrksyd** [comment]
I meant more so, I wasn't exactly sure how to implement what I wanted using egui so that's why I posted what I was going for.

**Comment by ScanMountGoat** [comment]
For the image you posted, the basic idea is to have two horizontal layouts inside of a vertical layout for the rows. You could try `ui.horizontal_centered` for each row for more consistent vertical spacing. Layouts in egui work best when they work top to bottom and left to right. It's possible to do a right to left layout like what you have for the frame value, but it's harder to get working due to limitations with immediate mode UI. I would just keep the frame value with the slider and play button for now.

**Comment by zrksyd** [comment]
![image](https://user-images.githubusercontent.com/6856627/184717925-00296702-fada-45f3-b409-9900636bf383.png)
What do you think of this? I think it's a bit of a compromise since I can't right align the frame count. I attempted to do something very silly where I added a ui.label("\t".repeat(x)); and x was some number that would be based on the ui.available_width (which is already being used by the slider) but it would've required a lot of adjustment to get the value just right.

**Comment by ScanMountGoat** [comment]
It's definitely an improvement. There are ways to manually add space or place controls at a fixed position with egui rather than relying on whitespace width. I wouldn't worry too much about the frame value. I'll probably end up incorporating the current frame into a custom slider similar to Maya or Blender anyway.

**Comment by zrksyd** [comment]
![image](https://user-images.githubusercontent.com/6856627/184750391-5bc69299-9b6d-42ff-9c05-d8aa97b801e4.png)
There is no way to make a checkbox's label appear on the left, but making a checkbox with a separate label does not allow you to click on the text to toggle it like other checkboxes. Which should I use?

**Comment by ScanMountGoat** [comment]
I would just use a regular checkbox with the text on the right. You can put the loop checkbox on the left to avoid having the check mark next to the speed text. You would need to make a custom checkbox control to put the text on the left, which probably isn't worth the effort just for this use case.
