### ISSUE TITLE
Where are the textures :o

### ISSUE THREAD

**Issue by SMABSYSTEMS** [ScanMountGoat/ssbh_editor#70]
Hello guys,
So I have a question/problem with SSBH Editor. So when I import a model it looks like this:

![help1](https://user-images.githubusercontent.com/84009225/184900292-201826d6-8f6b-467e-aa2a-fd870ce6a150.PNG)

As you can see, the model looks very weird. (When I imported the body of a Mythra Mod, I saw nothing, but I did saw an outline of her body when I hovered over the eye button next to '\model\body\c00' to the right.)

So I figured that I could change Render Settings. I changed the 'Debug Mode' to 'Basic' and then the model looked like this:

![help](https://user-images.githubusercontent.com/84009225/184899320-49b64d4f-0c49-4771-8c0b-4a21c64d1e9c.PNG)

As you can now see, the model looks better. (When I did this with the Mythra Mod, she did became visible like the spear above.)

But I just can't find out how to get the textures on the model, because that's what I want to use it for. I want to make custom skins, but before I test it out on the game, I want to get a preview in SSBH Editor, although I can't see my actual skin mod (since it doesn't apply the textures).

Can someone help me?

**Comment by ScanMountGoat** [comment]
There's an error on the bottom right. If you click the logs button, what does it say?

**Comment by SMABSYSTEMS** [comment]
I just opened SSBH and imported the spear again, I changed render settings to basic again and this is my Log now:

![help2](https://user-images.githubusercontent.com/84009225/184903334-a1f28610-2fbd-4c2e-b4c1-52b30cf0b206.PNG)

**Comment by ScanMountGoat** [comment]
Thanks for the details. It sounds like a compatibility issue of some kind. Let me know if you get the "failed to load nutexb error" again with a picture of the message.

What GPU do you have for your computer? You need a computer that can run Vulkan or DX12, which should be true for any system released in about the last 10 years. The application is running and loading models, so your system should be new enough. Make sure you have the latest drivers installed from your GPU manufacturer's website (intel, amd, nvidia).

**Comment by ScanMountGoat** [comment]
The texture thumbnails are loading fine, so it seems like everything is working. Try opening another folder like `mario/model/body/c00` and see if that works.

**Comment by SMABSYSTEMS** [comment]
I have NVidia, my laptop is from 2010 if I'm right.

But I just tried something out,
I first randomly clicked on 'model.numatb' and noticed this:

![help3](https://user-images.githubusercontent.com/84009225/184904975-66bd6deb-0c33-47c2-96d2-11a09d259453.PNG)

So I searched that one up in the 'Debug Mode' and changed it to that

![help4](https://user-images.githubusercontent.com/84009225/184905124-0e1df118-9be7-4066-89aa-539846367dc7.PNG)

And now it looks like this:

![help5](https://user-images.githubusercontent.com/84009225/184905172-a1bb462d-bcf2-4153-a3b3-d4c3dabb141e.PNG)
 
I don't think this is the correct way and I tried every option in the Debug Mode earlier, including these textures one and it didn't work for the Mythra Mod import. I see that the Mythra Mod doesn't include a model.numatb file :o

![help6](https://user-images.githubusercontent.com/84009225/184906025-f0369a41-e1b9-4e0d-8df8-faa544b3ab14.PNG)

Now I have something else in my Log too:
![help7](https://user-images.githubusercontent.com/84009225/184906257-b8d924a8-0b52-487c-8205-2cba475232bd.PNG)

I'll see if Mario works tomorrow, because I need to do something now, thnx for the help and please look if my information above can help us solve this :D

'Speak' you tomorrow (maybe?)

**Comment by Shinoda112** [comment]
i'm getting a similar issue on my model.
![log](https://user-images.githubusercontent.com/111443356/185161082-9ef6da64-deb7-45ab-a281-0ca01dfd46e7.png)

**Comment by ScanMountGoat** [comment]
That's just a warning. It's a good idea to fix that warning by regenerating the mipmaps for the textures, but it shouldn't be causing this issue. 

In order to figure out what the issue might be, I would look at the debug modes under Menu > Render Settings. Check the Texture0 and map1 debug modes to make sure the textures and UVs look correct. You can also click on the texture thumbnails in the files list to open the nutexb viewer.

It's possible that the main shader is being compiled slightly differently on some GPUs, but I would need more information to be sure. What GPU do you have in your computer @Shinoda112?

**Comment by Shinoda112** [comment]
@ScanMountGoat 
i am using a gtx 1660 Ti.
My case is weird, because when I import the smash vanilla models into blender 3.0 with the carlos tool I get these names in the materials instead of def_ or metal_ . I tried it on 3 characters and same problem.
![materiales](https://user-images.githubusercontent.com/111443356/185179490-87c82df2-e5f3-4dad-98fc-ca15c98d797f.png)

then when i open the vanilla character into the editor it looks normal.
![normal](https://user-images.githubusercontent.com/111443356/185179559-6c622fc3-1d89-439e-9444-9e730575b259.png)

anyway, I managed to create my model with those names. i replaced the nustxb files in the toolbox. 
But when i import my mod folder  into the smash editor the textures are completely lost. I have no idea what's going on. Maybe I should check the UVs in blender, but I'm new to this
![uvmaps](https://user-images.githubusercontent.com/111443356/185179632-fb84e3cc-da3f-47b1-a26d-6f49e92dc645.png)

in game the model is invisible. 
I'm giving up

**Comment by ScanMountGoat** [comment]
If vanilla models work fine in SSBH Editor, it's probably not an SSBH Editor bug. If the model looks white, that can mean that the textures aren't assigned properly. Check the model.numatb file in SSBH Editor. If you need help fixing this in SSBH Editor, you can try out the new discussion forum or ask on the modding discord. I've linked both below. I'd like to keep github issues to bugs and feature requests to keep things organized.

https://github.com/ScanMountGoat/ssbh_editor/discussions
https://discord.gg/ASJyTrZ
