### ISSUE TITLE
If two animations are loaded, set total animation length in playback to LCM.

### ISSUE THREAD

**Issue by zrksyd** [ScanMountGoat/ssbh_editor#71]
When two animations are loaded, it should load the lowest common multiple so the shorter animation can play in full. For example, if animation A is 6 frames long and animation B is 4 frames long. The slider should go to 12 frames so that they can repeat and loop seamlessly.

**Comment by ScanMountGoat** [comment]
There are two separate problems to tackle. The first is for each animation to loop individually rather than looping with the longest animation. The second is for the animations to loop like you described. In your example, the animation B would end at frame 4 of animation A the first time and frame 2 of of animation A the second time. I don't think this just changes anything compared to having the animation slider just display 6 frames.

**Comment by ScanMountGoat** [comment]
The solution you described would create seamless loops for certain cases like 600 and 48 frame animations. This behavior would be confusing in the UI, so I'm going to leave the looping as is. The latest commit has per animation looping, so this isn't a huge issue anymore in practice. One animation is often substantially longer than the other.
