### ISSUE TITLE
When i open it, it closes immediatly

### ISSUE THREAD

**Issue by kudake** [ScanMountGoat/ssbh_editor#74]
My system should meet the limitations listed on your page. I went on gamebanana and saw someone experiencing the same problem, however they have not openend an issue yet.
My PC information:

Operating system: Windows 10, 64-bit
GPU: nvidia 940M
(CPU: Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz   2.90 GHz)

please do not let it be the gpu :'''')

**Comment by ScanMountGoat** [comment]
There are two main issues that could cause this. The first issue is that you don't have the C++ 2015 runtime installed required by Rust, which is required for Rust programs to work on Windows. You can download it from https://www.microsoft.com/en-us/download/details.aspx?id=52685. I'll update the documentation since I forgot to mention this. You may already have this installed, but it's worth double checking.

The second issue is GPU compatibility issues. Your system has an integrated GPU (intel) and a discrete GPU (Nvidia). These should both be modern enough to run Vulkan or DX12.

**Comment by kudake** [comment]
i actually have all of these runtimes installed, also tried changing the gpu which runs the program, still no success

**Comment by kudake** [comment]
okay after deinstalling the .net core 3.1 runtimes i have installed prior for crossmodgui, upgrading to the 6.0 version and installing the ms visual c++ it SOMEHOW worked out. i cannot tell you how i got it and i actually tried it before commenting a second time but now it suddenly works.

**Comment by ScanMountGoat** [comment]
SSBH Editor doesn't require .NET Core like Cross Mod. It sounds like reinstalling the c++ runtime did the trick. If you're still having problems, you can reopen this issue or create a new issue. I've updated the installation instructions on the release and updated the system requirements.

**Comment by kudake** [comment]
i guess so. thank you for your support!
